 

function toolTestSecret(){
    return "Testing tool this is my secret, do you mind?"
}

export const sonarFirstAgent = async (query:string) => {
 const perplexityUrl = "https://api.perplexity.ai/chat/completions";
 const perplexityApiKey = process.env.NEXT_PUBLIC_PERPLEXITY_API_KEY;
 const systemPrompt = `
 You are the first step in an AI agent and you job is to detect if user query requeres the use of a tool or not.
    If the user query requires tool then you must respond with the JSON object strcture bellow:
    If use wants to use the secret tool or asks for a secret message with the query you only job will to respond with this->
    {
    tool_name: "test_secret",
    tool_input: "nothing",
    tool_reasoning: "secret"
    }
    if user wants to get the answer without any tool specific requirement just respond to query also always provide answer in json format so that my parser does not throw an error.
 `; // Define your system prompt here
try {
const requestBody ={
    model:"sonar",
    messages:[
        {
            role: "system",
            content: systemPrompt
        },
        {
            role: "user",
            content: query
        }
    ]
}
const response = await fetch(perplexityUrl, {
    method: "POST",
    headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${perplexityApiKey}`
    },
    body: JSON.stringify(requestBody)
});

if (!response.ok) {
    throw new Error(`Error: ${response.status} ${response.statusText}`);
}else {
    const data = await response.json();
    console.log("Sonar First Agent Response:", data.choices?.[0]?.message);
    const agentResponse = await JSON.parse(data.choices?.[0]?.message?.content);
    if(data.choices?.[0]?.message?.content && agentResponse?.tool_name === "test_secret"){
       console.log("Tool response generated by Sonar First Agent.");
        return `{
            tool_response: ${toolTestSecret()},
            user_query: ${query}
        }`;
        
    }else{
        return data.choices?.[0]?.message?.content;
    }
}

} catch (error) {
    console.error("Error in sonarFirstAgent:", error);
    throw error;
}


}